sequenceDiagram
  participant participant_createGooglePlayAndroidPublisher as createGooglePlayAndroidPublisher
  participant participant_createGooglePlayDeploymentProvider as createGooglePlayDeploymentProvider
  participant participant_createGooglePlayMonetizationAdapter as createGooglePlayMonetizationAdapter
  participant participant_createGooglePlayReleaseAdapter as createGooglePlayReleaseAdapter
  participant participant_createGooglePlaySetupAdapter as createGooglePlaySetupAdapter
  participant participant_createGooglePlayStoreListingAdapter as createGooglePlayStoreListingAdapter
  participant_createGooglePlayDeploymentProvider->>participant_createGooglePlaySetupAdapter: createGooglePlaySetupAdapter()
  participant_createGooglePlaySetupAdapter-->>participant_createGooglePlayDeploymentProvider: return
  participant_createGooglePlayDeploymentProvider->>participant_createGooglePlayAndroidPublisher: createGooglePlayAndroidPublisher()
  participant_createGooglePlayAndroidPublisher-->>participant_createGooglePlayDeploymentProvider: return
  participant_createGooglePlayDeploymentProvider->>participant_createGooglePlayStoreListingAdapter: createGooglePlayStoreListingAdapter()
  participant_createGooglePlayStoreListingAdapter-->>participant_createGooglePlayDeploymentProvider: return
  participant_createGooglePlayDeploymentProvider->>participant_createGooglePlayMonetizationAdapter: createGooglePlayMonetizationAdapter()
  participant_createGooglePlayMonetizationAdapter-->>participant_createGooglePlayDeploymentProvider: return
  participant_createGooglePlayDeploymentProvider->>participant_createGooglePlayReleaseAdapter: createGooglePlayReleaseAdapter()
  participant_createGooglePlayReleaseAdapter-->>participant_createGooglePlayDeploymentProvider: return
